### ISSUE TITLE
Expose functionality for query all credentials for a given did

### ISSUE THREAD

**Issue by PaddyMc** [elesto-dao/elesto#121]
Enhance the `grpc_query.go` functionality to query for all credentials to a given issuer 

https://github.com/elesto-dao/elesto/blob/main/proto/credential/v1/query.proto#L47

https://github.com/elesto-dao/elesto/blob/main/x/credential/keeper/grpc_query.go#L36-L50

**Comment by hpsing** [comment]
@PaddyMc should we change [the endpoint](https://github.com/elesto-dao/elesto/blob/9c57d8c395f049220b8f96cbc0f81064efdb8bed/proto/credential/v1/query.proto#L47)  from 

**/elesto/credential/issuer/{did}** to **/elesto/credential/definitions/publisher/{did}**.

because it clashes with [this](https://github.com/elesto-dao/elesto/blob/9c57d8c395f049220b8f96cbc0f81064efdb8bed/proto/credential/v1/query.proto#L32).

**Comment by PaddyMc** [comment]
Yeah thats perfect
