### ISSUE TITLE
feat: Inflation/gas implementation

### ISSUE THREAD

**Issue by dbg-dev** [elesto-dao/elesto#80]

**Comment by dbg-dev** [comment]
Gas code complete

**Comment by dbg-dev** [comment]
Inflation = config only
TODO: gas multiplier based on the size of Mempool

**Comment by simonjamaggs** [comment]
gas pricing for did creation and did update implemented in elesto.

research showed it is not possible to implement a gas multiplier based on the size of the mempool - this is because different nodes will 'run the transaction' at different times - i.e. when the mempool has different state. 

during week starting 18th April it was decided to move to a different/deterministic inflation model; this has been spec'd; implementation completed by Simon and Andrea on 27th April

**Comment by simonjamaggs** [comment]
![image.png](https://images.zenhubusercontent.com/6127847b4c842e84062dda0f/f856acef-c9a2-4a4a-8864-e23a2fc58efb)
